### ISSUE TITLE
Missing Czech fonts in the journal

### ISSUE THREAD

**Issue by Karselien** [lokinmodar/Echoglossian#111]
Hello, thank you for your work. I have one problem that I encountered while translating only journal settings. In the classic dialog view everything is fine and the Czech fonts are displayed perfectly. 

I am using the Czech translation and I have a problem with the special hook font characters. For the letters r, č, ů, ú, ě, ž etc. even after the latest version 3.12.x (where the missing fonts were fixed) I still get an error. Oddly enough the letter sh is fine. All the special characters could be replaced with just the classic r,c,u,e,z fonts without using a hook over the letter and the meaning would be understood. Better than broken text with an = type character. Thank you for a possible correction. If it could not be done anyway I am very happy for your work. 

<img width="470" alt="journal 1" src="https://github.com/user-attachments/assets/ac883371-0cc8-41b7-bb6d-6f07a4a221c5">
<img width="496" alt="journal" src="https://github.com/user-attachments/assets/00e9e3f6-37bc-4fde-a6c3-b6a500595100">
<img width="484" alt="journal 2" src="https://github.com/user-attachments/assets/7ff4b727-d50c-4b5b-9191-436214ac5e12">

<br>

Everything is ok in the dialogue:
<img width="1216" alt="in dialog is everything is ok" src="https://github.com/user-attachments/assets/9f69cf01-0e9e-4ded-a219-834bc7965053">

Thx.

**Comment by lokinmodar** [comment]
> Hello, thank you for your work. I have one problem that I encountered while translating only journal settings. In the classic dialog view everything is fine and the Czech fonts are displayed perfectly.
> 
> I am using the Czech translation and I have a problem with the special hook font characters. For the letters r, č, ů, ú, ě, ž etc. even after the latest version 3.12.x (where the missing fonts were fixed) I still get an error. Oddly enough the letter sh is fine. All the special characters could be replaced with just the classic r,c,u,e,z fonts without using a hook over the letter and the meaning would be understood. Better than broken text with an = type character. Thank you for a possible correction. If it could not be done anyway I am very happy for your work.
> 
> <img alt="journal 1" width="470" src="https://private-user-images.githubusercontent.com/149306015/355195516-ac883371-0cc8-41b7-bb6d-6f07a4a221c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODI1MTMsIm5iZiI6MTcyMjg4MjIxMywicGF0aCI6Ii8xNDkzMDYwMTUvMzU1MTk1NTE2LWFjODgzMzcxLTBjYzgtNDFiNy1iYjZkLTZmMDdhNGEyMjFjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODIzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2NkMzZmMTkwNGE1YjRiNjM5ZjU4ZjA3ZjNmMTFiMTdkNWYxYzMyOGMwNjFjODBmZDE1ODVjMGQ1NWZhNzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wf6QMo3A3eThLs4el_hkwbBqpZqr0aTALskykT7jcwM"> <img alt="journal" width="496" src="https://private-user-images.githubusercontent.com/149306015/355194860-00e9e3f6-37bc-4fde-a6c3-b6a500595100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODI1MTMsIm5iZiI6MTcyMjg4MjIxMywicGF0aCI6Ii8xNDkzMDYwMTUvMzU1MTk0ODYwLTAwZTllM2Y2LTM3YmMtNGZkZS1hNmMzLWI2YTUwMDU5NTEwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODIzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGU1NGU2Y2UxNDVjNGI4YWQyMDRmMGUzN2U1NmVmM2M0Zjk1Njk4NGI1MGMzMWQ2MTA5NjVkMTQ2MzMwYTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5rJMXtSgdgaIz4WNTCDAwKA26H1xwB67HeEmAXDV66o"> <img alt="journal 2" width="484" src="https://private-user-images.githubusercontent.com/149306015/355195547-7ff4b727-d50c-4b5b-9191-436214ac5e12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODI1MTMsIm5iZiI6MTcyMjg4MjIxMywicGF0aCI6Ii8xNDkzMDYwMTUvMzU1MTk1NTQ3LTdmZjRiNzI3LWQ1MGMtNGI1Yi05MTkxLTQzNjIxNGFjNWUxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODIzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzcxMzk3YWQyNzczNzJmNzVjYWQ4MDc5NTU1NmRlZGU5Y2ExYzBiY2ZlYzNkYzVkNzQ2YjA5NjQ3MWQ2NDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xzzy0EKDcTn4M3wqiZte82mMO-IR3o4n0ujdpVWiuB4">
> Everything is ok in the dialogue: <img alt="in dialog is everything is ok" width="1216" src="https://private-user-images.githubusercontent.com/149306015/355195668-9f69cf01-0e9e-4ded-a219-834bc7965053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODI1MTMsIm5iZiI6MTcyMjg4MjIxMywicGF0aCI6Ii8xNDkzMDYwMTUvMzU1MTk1NjY4LTlmNjljZjAxLTBlOWUtNGRlZC1hMjE5LTgzNGJjNzk2NTA1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODIzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTNjYTVkN2VhNmIxYTkwOGJjNGYyZmZjZTZmMjNjMDkwZjdiMzJjODA4ZjE5YmU1MGE3ZDdlNTBjNjVkNDE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5AZl1xksO8xAkK_tQMm0N3UBcjzXVac6Orlo5gky_c8">
> 
> Thx.

it is indeed a nice idea for languages that use Latin Extended like Czech, Polish and Vietnamese while we don't find a better solution. I'll add this to the backlog and make some tests! maybe add this as an option for these languages 
:)

**Comment by Karselien** [comment]
> > Hello, thank you for your work. I have one problem that I encountered while translating only journal settings. In the classic dialog view everything is fine and the Czech fonts are displayed perfectly.
> > I am using the Czech translation and I have a problem with the special hook font characters. For the letters r, č, ů, ú, ě, ž etc. even after the latest version 3.12.x (where the missing fonts were fixed) I still get an error. Oddly enough the letter sh is fine. All the special characters could be replaced with just the classic r,c,u,e,z fonts without using a hook over the letter and the meaning would be understood. Better than broken text with an = type character. Thank you for a possible correction. If it could not be done anyway I am very happy for your work.
> > <img alt="journal 1" width="470" src="https://private-user-images.githubusercontent.com/149306015/355195516-ac883371-0cc8-41b7-bb6d-6f07a4a221c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODI1MTMsIm5iZiI6MTcyMjg4MjIxMywicGF0aCI6Ii8xNDkzMDYwMTUvMzU1MTk1NTE2LWFjODgzMzcxLTBjYzgtNDFiNy1iYjZkLTZmMDdhNGEyMjFjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODIzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2NkMzZmMTkwNGE1YjRiNjM5ZjU4ZjA3ZjNmMTFiMTdkNWYxYzMyOGMwNjFjODBmZDE1ODVjMGQ1NWZhNzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wf6QMo3A3eThLs4el_hkwbBqpZqr0aTALskykT7jcwM"> <img alt="journal" width="496" src="https://private-user-images.githubusercontent.com/149306015/355194860-00e9e3f6-37bc-4fde-a6c3-b6a500595100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODI1MTMsIm5iZiI6MTcyMjg4MjIxMywicGF0aCI6Ii8xNDkzMDYwMTUvMzU1MTk0ODYwLTAwZTllM2Y2LTM3YmMtNGZkZS1hNmMzLWI2YTUwMDU5NTEwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODIzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGU1NGU2Y2UxNDVjNGI4YWQyMDRmMGUzN2U1NmVmM2M0Zjk1Njk4NGI1MGMzMWQ2MTA5NjVkMTQ2MzMwYTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5rJMXtSgdgaIz4WNTCDAwKA26H1xwB67HeEmAXDV66o"> <img alt="journal 2" width="484" src="https://private-user-images.githubusercontent.com/149306015/355195547-7ff4b727-d50c-4b5b-9191-436214ac5e12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODI1MTMsIm5iZiI6MTcyMjg4MjIxMywicGF0aCI6Ii8xNDkzMDYwMTUvMzU1MTk1NTQ3LTdmZjRiNzI3LWQ1MGMtNGI1Yi05MTkxLTQzNjIxNGFjNWUxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODIzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzcxMzk3YWQyNzczNzJmNzVjYWQ4MDc5NTU1NmRlZGU5Y2ExYzBiY2ZlYzNkYzVkNzQ2YjA5NjQ3MWQ2NDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xzzy0EKDcTn4M3wqiZte82mMO-IR3o4n0ujdpVWiuB4">
> > Everything is ok in the dialogue: <img alt="in dialog is everything is ok" width="1216" src="https://private-user-images.githubusercontent.com/149306015/355195668-9f69cf01-0e9e-4ded-a219-834bc7965053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODI1MTMsIm5iZiI6MTcyMjg4MjIxMywicGF0aCI6Ii8xNDkzMDYwMTUvMzU1MTk1NjY4LTlmNjljZjAxLTBlOWUtNGRlZC1hMjE5LTgzNGJjNzk2NTA1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODIzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTNjYTVkN2VhNmIxYTkwOGJjNGYyZmZjZTZmMjNjMDkwZjdiMzJjODA4ZjE5YmU1MGE3ZDdlNTBjNjVkNDE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5AZl1xksO8xAkK_tQMm0N3UBcjzXVac6Orlo5gky_c8">
> > Thx.
> 
> it is indeed a nice idea for languages that use Latin Extended like Czech, Polish and Vietnamese while we don't find a better solution. I'll add this to the backlog and make some tests! maybe add this as an option for these languages :)

Hi, that would be great. I'd just ask that only the text in the journal be resolved this way, because the dialogue translation is fully functional, including the diacritics, the hooks over the letters. Thank you.

**Comment by lokinmodar** [comment]
> > > Hello, thank you for your work. I have one problem that I encountered while translating only journal settings. In the classic dialog view everything is fine and the Czech fonts are displayed perfectly.
> > > I am using the Czech translation and I have a problem with the special hook font characters. For the letters r, č, ů, ú, ě, ž etc. even after the latest version 3.12.x (where the missing fonts were fixed) I still get an error. Oddly enough the letter sh is fine. All the special characters could be replaced with just the classic r,c,u,e,z fonts without using a hook over the letter and the meaning would be understood. Better than broken text with an = type character. Thank you for a possible correction. If it could not be done anyway I am very happy for your work.
> > > <img alt="journal 1" width="470" src="https://private-user-images.githubusercontent.com/149306015/355195516-ac883371-0cc8-41b7-bb6d-6f07a4a221c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODI1MTMsIm5iZiI6MTcyMjg4MjIxMywicGF0aCI6Ii8xNDkzMDYwMTUvMzU1MTk1NTE2LWFjODgzMzcxLTBjYzgtNDFiNy1iYjZkLTZmMDdhNGEyMjFjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODIzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2NkMzZmMTkwNGE1YjRiNjM5ZjU4ZjA3ZjNmMTFiMTdkNWYxYzMyOGMwNjFjODBmZDE1ODVjMGQ1NWZhNzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wf6QMo3A3eThLs4el_hkwbBqpZqr0aTALskykT7jcwM"> <img alt="journal" width="496" src="https://private-user-images.githubusercontent.com/149306015/355194860-00e9e3f6-37bc-4fde-a6c3-b6a500595100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODI1MTMsIm5iZiI6MTcyMjg4MjIxMywicGF0aCI6Ii8xNDkzMDYwMTUvMzU1MTk0ODYwLTAwZTllM2Y2LTM3YmMtNGZkZS1hNmMzLWI2YTUwMDU5NTEwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODIzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGU1NGU2Y2UxNDVjNGI4YWQyMDRmMGUzN2U1NmVmM2M0Zjk1Njk4NGI1MGMzMWQ2MTA5NjVkMTQ2MzMwYTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5rJMXtSgdgaIz4WNTCDAwKA26H1xwB67HeEmAXDV66o"> <img alt="journal 2" width="484" src="https://private-user-images.githubusercontent.com/149306015/355195547-7ff4b727-d50c-4b5b-9191-436214ac5e12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODI1MTMsIm5iZiI6MTcyMjg4MjIxMywicGF0aCI6Ii8xNDkzMDYwMTUvMzU1MTk1NTQ3LTdmZjRiNzI3LWQ1MGMtNGI1Yi05MTkxLTQzNjIxNGFjNWUxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODIzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzcxMzk3YWQyNzczNzJmNzVjYWQ4MDc5NTU1NmRlZGU5Y2ExYzBiY2ZlYzNkYzVkNzQ2YjA5NjQ3MWQ2NDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xzzy0EKDcTn4M3wqiZte82mMO-IR3o4n0ujdpVWiuB4">
> > > Everything is ok in the dialogue: <img alt="in dialog is everything is ok" width="1216" src="https://private-user-images.githubusercontent.com/149306015/355195668-9f69cf01-0e9e-4ded-a219-834bc7965053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODI1MTMsIm5iZiI6MTcyMjg4MjIxMywicGF0aCI6Ii8xNDkzMDYwMTUvMzU1MTk1NjY4LTlmNjljZjAxLTBlOWUtNGRlZC1hMjE5LTgzNGJjNzk2NTA1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODIzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTNjYTVkN2VhNmIxYTkwOGJjNGYyZmZjZTZmMjNjMDkwZjdiMzJjODA4ZjE5YmU1MGE3ZDdlNTBjNjVkNDE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5AZl1xksO8xAkK_tQMm0N3UBcjzXVac6Orlo5gky_c8">
> > > Thx.
> > 
> > 
> > it is indeed a nice idea for languages that use Latin Extended like Czech, Polish and Vietnamese while we don't find a better solution. I'll add this to the backlog and make some tests! maybe add this as an option for these languages :)
> 
> Hi, that would be great. I'd just ask that only the text in the journal be resolved this way, because the dialogue translation is fully functional, including the diacritics, the hooks over the letters. Thank you.

Available in version 3.14.x <3

**Comment by Karselien** [comment]
Hi, thank you for your work. I had the opportunity to test yesterday and everything is working as expected. Coffee is on its way, thanks for your great work.
