### ISSUE TITLE
This plugin failed to load. Please contact the author for more information. [v3.12.2408.1388]

### ISSUE THREAD

**Issue by axkigahara77** [lokinmodar/Echoglossian#113]
Hello, got this problem today after i log off to generate API key for CHAT GPT (pre log out plugin loaded normally).
What can i do to solve the problem? Installed via Dalamud, sorry to bother, but im not very familiar with FFXIV plugin systems

**Comment by lokinmodar** [comment]
hello! There is an issue with the config field for the chatgpt API key. I'm submitting a fix for this

**Comment by axkigahara77** [comment]
> hello! There is an issue with the config field for the chatgpt API key. I'm submitting a fix for this

Thanks for your work! Any ETA?

**Comment by lokinmodar** [comment]
> > hello! There is an issue with the config field for the chatgpt API key. I'm submitting a fix for this
> 
> Thanks for your work! Any ETA?

Update was submitted for approval. We need to wait for it to be published by Dalamud
