### ISSUE TITLE
Text is not shown during translation

### ISSUE THREAD

**Issue by MarYaInFour** [lokinmodar/Echoglossian#120]
When translating with google translator, the dialog box becomes completely blank.
![image](https://github.com/user-attachments/assets/5c61fb8c-bd9f-4457-9a5e-30a98c919fd6)
And when I use DeepL the text is just duplicated but not translated.
![image](https://github.com/user-attachments/assets/0a34bf1b-5749-4f85-bf1d-508724a57f2a)

**Comment by MarYaInFour** [comment]
This is what I have enabled in my settings.
![image](https://github.com/user-attachments/assets/a9380f57-f120-4612-9abb-ac68bb30c8e4)

**Comment by lokinmodar** [comment]
Thanks for the info. I received reports that google translate is being blocked in Russia. I'll check about DeepL. Have you tried using a VPN to mask your connection? If so, can you try to route google's urls through it?

**Comment by MarYaInFour** [comment]
I didn't use a VPN to mask the connection but now tried connecting and it worked, thanks for the quick help <3

**Comment by lokinmodar** [comment]
I'm assuming it is solved then <3
