### ISSUE TITLE
Currently used font is missing Polish letters

### ISSUE THREAD

**Issue by Barley194** [lokinmodar/Echoglossian#13]
![2021-10-10 17_01_43-ZeffUI](https://user-images.githubusercontent.com/20290894/136701509-6196c2b1-8c52-4a76-8d80-6ff25afc96af.png)
![2021-10-10 17_01_11-2021-10-10_16-51-58-621_OMGEorzea Gameplay png ‎- Zdjęcia](https://user-images.githubusercontent.com/20290894/136701510-7953c4e3-9212-4a5e-91b2-3441d9787e8f.png)

Is it possible to change the font to anything else which has those letters? (ąśćłęó) 
It could be either globally or only for Polish language.

example fonts: Consolas, Times New Roman

**Comment by lokinmodar** [comment]
It is a known issue. I'm working on setting the font based on translation
language. The fix is coming soon

Em dom, 10 de out de 2021 12:08, Barley194 ***@***.***>
escreveu:

**Comment by Barley194** [comment]
Thanks a lot for that. Works like a charm!
