### ISSUE TITLE
Plugin config screen appears every game launch

### ISSUE THREAD

**Issue by Roman-Sch** [lokinmodar/Echoglossian#14]
And language to translate always english (yes, i can change it and its save during game session)

**Comment by lokinmodar** [comment]
Can you please try deleting the ``Echoglossian.json`` and ``Echoglossian``
folder inside the ``%appdata%\XIVLauncher\pluginConfigs`` directory and
relaunch the game to see if it solves the issue?

**Comment by Roman-Sch** [comment]
Thanks, it fixes!
