### ISSUE TITLE
Overlay can't use cyrillic letters. 

### ISSUE THREAD

**Issue by ErinStarr** [lokinmodar/Echoglossian#16]
![ffxiv_dx11_Dvf3pd7Mi4](https://user-images.githubusercontent.com/92636464/137590132-236ba1b5-14e9-41f8-920e-1104720ea303.png)
![ffxiv_dx11_zNhBEVHc4T](https://user-images.githubusercontent.com/92636464/137590135-239419fa-4f1e-4c0c-a78d-80804dc7d248.png)

**Comment by lokinmodar** [comment]
It is a known issue. I'm working to pushing an update to fix this soon

**Comment by lokinmodar** [comment]
Fixed in the current version. Please update through FFXIVQuickLauncher
