### ISSUE TITLE
[Bug] Pause while rendering dialogue window

### ISSUE THREAD

**Issue by Bluefissure** [lokinmodar/Echoglossian#17]
When the dialogue windows pop up in cutscenes there'll be an obvious pause of rendering. I think it's caused by fetching the translated text from the API synchronously, which blocks the rendering procedure.

Is it possible to change it to async when replacing the text?

**Comment by lokinmodar** [comment]
Doing some tests on my end. The routines are not yet ready for deployment in the next release yet. I'll release a new version without this for dialogues for now but i hopefully will have a solution for the micro-stutters on all scenarios in the subsequent release

**Comment by VictorPozoSallent** [comment]
I was gonna comment you the same of micro cuts, but ive seen someone already did it, keep up the work. You re doing an essential thing for alot of people, thanks alot.

Also, i unable system tranlation and it seems changes dotn aply becuase it still tranlates me some system things. One last quick question, when you release the version with no cuts, do i have to do something or it will auto update, thanks again.

**Comment by lokinmodar** [comment]
Hello and thanks for the feedback! When it comes out your plugin will be
auto-updated by FFXIVQuickLauncher. If there is some new option in the
configs i'll let the users know through the release notes.

Em dom., 7 de nov. de 2021 às 19:03, VictorPozoSallent <
***@***.***> escreveu:

**Comment by VictorPozoSallent** [comment]
Thanks for the quick answer, and hopefully the micro cuts will be fixed soon, already uninstalled tataru, thanks for your job

Also quick question, did you though of implementig others translators like DeepL? :D

**Comment by SamaelDark** [comment]
Hi. The problem with microfreezes has been around for some time. The animation stops and the dialog box appears _without translation_. This happens 80% of the time. In fact, the plugin doesn't work.

**Comment by lokinmodar** [comment]
> Hi. The problem with microfreezes has been around for some time. The animation stops and the dialog box appears _without translation_. This happens 80% of the time. In fact, the plugin doesn't work.

Yes indeed. I am having some problems due to work schedule and couldn't release a new version since the last one. Also, the translations not happening issue surfaced because Google is sending different responses when the plugin calls the api. I already have a fix for this specific issue but could not tie up the code for a new release yet. I may be able to do so by the next weekend. Sorry for all the trouble

**Comment by VictorPozoSallent** [comment]
This isnt sovled yet right? Im having same problem even if im suing 3.0 ver.

**Comment by lokinmodar** [comment]
Yes. Not solved yet. I'm working on it (slowly, yes, but still working on
it)

**Comment by lokinmodar** [comment]
Solved in v3.5.x and later versions
