### ISSUE TITLE
Can't use old translation mode

### ISSUE THREAD

**Issue by NobeUnited** [lokinmodar/Echoglossian#21]
Hi,

I'm trying to use the old translation mode but I can't uncheck the option for the black window which now translates everything.

**Comment by lokinmodar** [comment]
Hello! I'm sorry for this error. I messed up bad. The toggle is missing from the config UI.

You can try (while out of the game) checking the `Echoglossian.json` settings file with in the `%appdata%\XIVLauncher\pluginConfigs` and changing the values of the two settings below to `false`, saving the config file and reloading the game:

`"UseImGui": true,`
`"UseImGuiForBattleTalk": true,`

**Comment by lokinmodar** [comment]
Fixed in the current release! <3
