### ISSUE TITLE
Plugin Config Window not showing

### ISSUE THREAD

**Issue by starnstripe** [lokinmodar/Echoglossian#23]
Hi there,

My plugin config window isn't showing when i type in /eglo

Thank you!

**Comment by reyculebrilla** [comment]
I ve the same error, do u have endwalker? i haven't it and i think thats the error maybe, a friend that has endwalker works perfectly , i hope they gave us a answer soon! 

Thank u too :D

**Comment by lokinmodar** [comment]
Please test the new release to see if it is fixed

**Comment by mtsaccorsi** [comment]
Same problem here. I'm testing the trial and I can install the plugin, but the config menu doesn't open either way. Others plugins open with no problem.

Edit: Closing the FPS counter solved my problem.

**Comment by lokinmodar** [comment]
> Same problem here. I'm testing the trial and I can install the plugin, but the config menu doesn't open either way. Others plugins open with no problem.
> 
> Edit: Closing the FPS counter solved my problem.

wait, what? i'll look into this but need more details. Is it the FPSPlugin counter?

**Comment by Grionis** [comment]
I solved this bug with the new version released, but i needed reboot the game and could see the configuration window

**Comment by lokinmodar** [comment]
> I solved this bug with the new version released, but i needed reboot the game and could see the configuration window

good to know. i still need to fix another issue i found in that window but it shouldn't stop ppl from using the plugin. In case of any error, please delete the `Echoglossian.json` file inside the `%appdata%\XIVLauncher\pluginConfigs` folder and restart the game

**Comment by alexkleinubing** [comment]
I already deleted json file (and everything too xD) but I cant open the config window to select language. :/

**Comment by Sickfiend** [comment]
Same here, pls tell me if u fix it @alexkleinubing

**Comment by lokinmodar** [comment]
Fixed in the latest release. If you still get the error, reload the game after installing the plugin
