### ISSUE TITLE
please delete Chinese Simplified support or set it default to Chinese Tranditional

### ISSUE THREAD

**Issue by TravorZhu** [lokinmodar/Echoglossian#24]
Final Fantasy XIV cannot show Chinese Simplified characters but can show Chinese Traditional characters.
Please delete Chinese Simplified support or set it to default to Chinese Traditional
![image](https://user-images.githubusercontent.com/26377201/145933469-a9de76f5-6b15-4d53-a997-9436e564837a.png)

**Comment by lokinmodar** [comment]
The solution here is (at least for ImGui  windows) is to add both char ranges (SC and TC) to the font building logic. I'll make some tests to see if this works or not. If it does, I will include it in the next plugin update. If it doesn't i'll try the proposed solution.

**Comment by lokinmodar** [comment]
Fixed in the current release
