### ISSUE TITLE
All characters have been changed ??? in UI

### ISSUE THREAD

**Issue by evandde** [lokinmodar/Echoglossian#25]
![image](https://user-images.githubusercontent.com/57508537/146664648-b12b1cb5-c20f-4377-96c7-0c5521327d9a.png)

Thx for your development.

Recently, I've got a problem that all characters related eglo changed into "???"; please see attached pictures.
I think this problem occured after 2.1.2112.174 (not exact), (You said that this version have a known issue that it should be turned on admin previlige to open setting window.)

I tried to install only eglo without any other plugins, but it showed same problem.
Before installing eglo, it displays proper english UI, but after installing eglo, it turns into ??? marks.

plz help me.

**Comment by lokinmodar** [comment]
Hello! I'm sorry you are having this issue.  Can you tell me which the following languages are being used by you?

- *System (windows) language*
- *Game UI language*
- *Language to translate to*

I see it is affecting the installer window and I have some clues on what could be happening but need the info above so I can confirm it is what I think it is and propose/find a solution.

Looking forward to your reply!

**Comment by evandde** [comment]
- System (Windows) language: Korean (windows 10 and 11 tested)
- Game UI language: EN, JP tested; same result above (lots of ??? characters)
- Language to translate to: JP, Korean tested;
   In JP, the UI is still displayed in ??? characters, but translation results of npc dialogue or toast messages are well displayed in japanese.
   In KR, all characters are displayed in ??? characters, including translation results and plugin UI.

- FYI, Dalamud Language is English.

---

Additional Info.

I have changed Windows language into English. In this case, the UI is well displayed in english characters.

However, when I select Korean as "Language to translate to", the translation results are shown in ??? characters.

Translating to Japanese is working well...

![image](https://user-images.githubusercontent.com/57508537/146681320-14bcdb7b-8e55-4cce-9bc9-d0967c045111.png)

**Comment by lokinmodar** [comment]
> * System (Windows) language: Korean (windows 10 and 11 tested)
> * Game UI language: EN, JP tested; same result above (lots of ??? characters)
> * Language to translate to: JP, Korean tested;
>   In JP, the UI is still displayed in ??? characters, but translation results of npc dialogue or toast messages are well displayed in japanese.
>   In KR, all characters are displayed in ??? characters, including translation results and plugin UI.
> * FYI, Dalamud Language is English.
> 
> Additional Info.
> 
> I have changed Windows language into English. In this case, the UI is well displayed in english characters.
> 
> However, when I select Korean as "Language to translate to", the translation results are shown in ??? characters.
> 
> Translating to Japanese is working well...
> 
> ![image](https://user-images.githubusercontent.com/57508537/146681320-14bcdb7b-8e55-4cce-9bc9-d0967c045111.png)

Thanks for the info. I'll make some tests on my end and try to fix this for the next release!

**Comment by lokinmodar** [comment]
Fixed in the current release
