### ISSUE TITLE
Game suddenly close

### ISSUE THREAD

**Issue by Axelrhoads** [lokinmodar/Echoglossian#26]
Hi, thank you for working in this awesome plugin.
It seems that the game closes when a dialog line will appear in the center of the screen. 

The visor events give me this error:

![imagen](https://user-images.githubusercontent.com/52333796/146672968-44aec24d-09de-4b1b-aaa5-500afc332b1b.png)

It works perfectly if i disable the addon.
Thank you.

**Comment by lokinmodar** [comment]
Hello! I'm sorry you are having this issue. I'd like to ask you to send me your dalamud.log file that is available in `%appdata%\XIVLauncher` folder when that error occurs so I can see if there is some underlying problem happening. You can find me on Discord by the name DanteSS#2200 or via e-mail (lokinmodar@gmail.com)

**Comment by lokinmodar** [comment]
Hello!

By the data you sent i see the plugin is not creating its database. Can you do the following test:

Go to the `%appdata%\XIVLauncher\pluginConfigs` folder and delete the `Echoglossian.json` file and the `Echoglossian` folder and try to reload the plugin to see if it will give you any error.

Tell me what happens next.

**Comment by lokinmodar** [comment]
Closing this as there was no response from the user for a month. I'm assuming everything is ok for now.
