### ISSUE TITLE
BUG - CANT Select the option boxes to translate

### ISSUE THREAD

**Issue by peehenriqueb** [lokinmodar/Echoglossian#27]
The addon dont let me click on the boxes for translate, i already reinstaled and deleted the folders and still like that

![image](https://user-images.githubusercontent.com/47677328/146926631-987d6103-bb2d-4263-a564-37367024ec3c.png)

**Comment by lokinmodar** [comment]
Hello. I'm sorry for this issue. I'm currently working to solve it. Other job assignments are making me take too long to fix this. My apologies!

**Comment by davaiteee** [comment]
I had the same issue and found how to solve it. I changed language to kazakh (dont ask why, i just did) and all boxes became clickable

**Comment by lokinmodar** [comment]
> I had the same issue and found how to solve it. I changed language to kazakh (dont ask why, i just did) and all boxes became clickable

Actually just changing to any other language in the list refreshes the UI

**Comment by alexkleinubing** [comment]
+1

Can I change directly on any config file?

**Comment by lokinmodar** [comment]
> +1
> 
> Can I change directly on any config file?

You can change at the config window itself selecting a different language but if you want to change the plugin config file in `%appdata%\XIVLauncher\pluginConfigs\Echoglossian.json`. There is a field called `"Lang"`. Accepted values are between 0 and 118

**Comment by lokinmodar** [comment]
Fixed in the current release
