### ISSUE TITLE
Game microfrezzes and sometimes it doesn't translate the dialogue

### ISSUE THREAD

**Issue by MrPwner01** [lokinmodar/Echoglossian#29]
So yeah, any dialogue causes the game to "freeze" for few frames, sometimes the dialogue doesn't get translated, what's the issue here? Sorry english is not my primary language

**Comment by lokinmodar** [comment]
Hello!
The micro-freezes are due to some sync code i'm refactoring to async.
The missing translation every now and then is due to an error in google translate API response. I noticed it too and it is already fixed for the next release.

**Comment by Sickfiend** [comment]
having same problem over here, lot of microfreezes

**Comment by lokinmodar** [comment]
Closing this as it is a known issue and it is being reworked. No ETA to release the fixes but I ask you to bear with us.
