### ISSUE TITLE
Overlay Translation fails sometimes. 

### ISSUE THREAD

**Issue by PedroMandu** [lokinmodar/Echoglossian#30]
Hi, first, thanks for the plugin, it's really awesome!
I'd like to contribute to a problem I've encountered and I can test it when needed. 

Sometimes the translation simply skips the dialogue.
Usually the glitch occurs after a delay in frames, as if it were a drop in FPS. 

My config:
Dell G5 15 5590
RTX 2060
Intel I7 9750
RAM: 32GB
Installed in NVME 2.

![Final Fantasy XIV  A Realm Reborn Screenshot 2022 01 24 - 19 23 48 95](https://user-images.githubusercontent.com/24882685/150875586-45e29325-0bdf-4396-ba4d-4353fdf47340.jpg)
![Final Fantasy XIV  A Realm Reborn Screenshot 2022 01 24 - 19 24 15 20](https://user-images.githubusercontent.com/24882685/150875589-85fcf56f-9947-478a-8648-b509dc92b09f.jpg)
![Config Plugin](https://user-images.githubusercontent.com/24882685/150875753-b06fa3aa-cad2-4d23-adfc-8c9ac87fba3f.jpg)
0

**Comment by lokinmodar** [comment]
Hello! it isn't a config error. Google just changed the response from their API and I am fixing the code to take their changes into account for the next release. Please look forward to it!

**Comment by Web-NAVI** [comment]
Is this the same as "Waiting for translation..." but without an actual message showing up, or is it something else causing it?
I was about to make another post because many times i get this "Waiting for translation..." and i'd rather ask than make another post about the same issue.

**Comment by lokinmodar** [comment]
> Is this the same as "Waiting for translation..." but without an actual message showing up, or is it something else causing it? I was about to make another post because many times i get this "Waiting for translation..." and i'd rather ask than make another post about the same issue.

It is caused by the same issue I pointed, yes

**Comment by Sickfiend** [comment]
Just wanted to say that im having the same issue with spanish translation, thanks again for the awesome mod, looking forward to it

**Comment by GasmasKoo** [comment]
> Hello! it isn't a config error. Google just changed the response from their API and I am fixing the code to take their changes into account for the next release. Please look forward to it!

I am glad to hear this, this mod totally changed my experience with the game, thank you very very much. ♥

**Comment by elizeuW** [comment]
ola Quais dias vai atualizar? Ou tradutor?

**Comment by elizeuW** [comment]
hello What days will you update? Or translator?

**Comment by lokinmodar** [comment]
> hello What days will you update? Or translator?

I'm working hard to release by next Monday if everything goes well

**Comment by Mukaaxz** [comment]
@lokinmodar Hello! Please when you are going to update the plugin to solve the translation engine? can you add a private api key feature? in order to use a "pay to use google api key"?

**Comment by lokinmodar** [comment]
It is in the works. Icma adding this option too

Em sex, 25 de fev de 2022 11:58, Mukaaxz ***@***.***>
escreveu:

**Comment by lokinmodar** [comment]
Solved in the latest version!
