### ISSUE TITLE
Translation is not working

### ISSUE THREAD

**Issue by DaemonArev** [lokinmodar/Echoglossian#32]
From today the translation is not working completely! Until this day, the translation worked 50/50. But today for several hours the plugin has never translated a single message. Pls repair plugin, its a best plugin in game!

**Comment by lokinmodar** [comment]
Sorry for the trouble. Google changed its API and I'm working on the fix. I want to release it soon

**Comment by DaemonArev** [comment]
oh my god, I'm waiting for this fix very much, thx!
