### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by DevNataneto** [lokinmodar/Echoglossian#33]
Do you have a date for the next update? I miss playing the game with the translation :D

**Comment by Szebike** [comment]
Same :( still waiting for play with the translation.

**Comment by lokinmodar** [comment]
Please hold on a little bit more. I'm working hard to release a new version soon. My apologies.

**Comment by GasmasKoo** [comment]
You don't have to apologize, you are amazing. take all the time you need!

**Comment by DevNataneto** [comment]
Yeaaah, that's okay, i just wanted to know if there was already an update

Take your time <3

**Comment by ericksinm12** [comment]
I miss this tool so much but take the time you need..

I just create this account to give you a big thanks. we appreciate your work

**Comment by M4rcosFelipe** [comment]
Do you need help? If so, you can tell us what you need.

**Comment by lokinmodar** [comment]
> Do you need help? If so, you can tell us what you need.

Hello! It is more a question of time than anything. I'm working on the update and it still need more adjustments and hopefully i'm releasing a new version soon. Work is consuming most of my time but i'm commited to releasing a new version ASAP

**Comment by biia-sweetheart** [comment]
Hi!!! 
Thank you so much for the update, your work is very important for many people, included for me! <3 

Take your time <3 <3 <3

**Comment by LucasBLs** [comment]
Hi! First, congratulations on the project!

The translation is still not working right?

**Comment by elizeu8111** [comment]
There's a day scheduled to do the Update!!?

**Comment by GasmasKoo** [comment]
Have you given up on this? It's ok, hey. I want to know so i just continue the MSQ in English. You did an amazing work, i really enjoy this while it lasted.

**Comment by lokinmodar** [comment]
I did not give up. It is just that work and health issues are overwhelming
me. I'm slowly getting things under control and will have some update
before 6.1 arrives. Thanks for understanding and sorry for the delays

Em sáb, 2 de abr de 2022 05:36, GasmasKoo ***@***.***>
escreveu:

**Comment by lokinmodar** [comment]
Closing this issue. Please see #12 

Just waiting for approval and the plugin should be back to XIVLauncher!
