### ISSUE TITLE
Echo sumiu?''

### ISSUE THREAD

**Issue by jaskierpankratz** [lokinmodar/Echoglossian#35]
Ola, amo seu trabalho e o Echo, vi q foi atualizado a algumas horas atraz, porem no Dallamud plugin ele n esta aparecendo, demora um tempo para ele voltar apos uma atualização?

**Comment by lokinmodar** [comment]
> Ola, amo seu trabalho e o Echo, vi q foi atualizado a algumas horas atraz, porem no Dallamud plugin ele n esta aparecendo, demora um tempo para ele voltar apos uma atualização?

O plugin foi desativado por estar causando um problema com a nova versão do jogo após o update. Eu estou corrigindo isso, e assim que ele voltar, o download estará disponível novamente pelo instalador de plugins.
