### ISSUE TITLE
Cant install through FFXIVQuickLauncher

### ISSUE THREAD

**Issue by DucNguyen0812** [lokinmodar/Echoglossian#36]
i used the lastet version of the Quicklauncher but i could not your plugin to install, what did i do wrong, plz help!

**Comment by cypiate** [comment]
Project is lost probably :( Very sad.

**Comment by lokinmodar** [comment]
Not lost. I'm releasing a new update soon. The plugin was disabled due to a
bug impacting other plugins

Em seg, 4 de abr de 2022 03:03, cypiate ***@***.***> escreveu:

**Comment by sjkdfhwu** [comment]
Please, update this!!
Can I install older version manually? If so I need to compile the source code myself?
This is a very unique project, please don't let it die

**Comment by cypiate** [comment]
Alot ppl waiting and waiting ... As i said project closed.

**Comment by lokinmodar** [comment]
> Alot ppl waiting and waiting ... As i said project closed.

You want to help?? Or just troll? 

As the owner of the repo said (me) the project IS NOT DEAD. This is a one-man's hobby work and life constraints happen (surgery, job and need for money). The update will come out when it comes out unless someone wants to help in a proper way: CONTRIBUTING to the project (maybe forking and PRing a fix if one cannot wait?).

I'll close this and make sure to not answer snide comments.

**Comment by lokinmodar** [comment]
> Please, update this!! Can I install older version manually? If so I need to compile the source code myself? This is a very unique project, please don't let it die

Please read the response above.

**Comment by lokinmodar** [comment]
And a new game patch is out and Dalamud plugins were disabled until the core dalamud was fixed. I'm checking dalamud status to see if everything is functional on their part again.
