### ISSUE TITLE
CJK fonts issue

### ISSUE THREAD

**Issue by KihwaH** [lokinmodar/Echoglossian#37]
Hi, I really appreciate the update today. Your plugin really helped playing 6.0 before it stopped working.

As far as I remember Korean displayed fine back then, but for some reason now it's missing Korean fonts now.

![1](https://user-images.githubusercontent.com/56755347/163797817-81436828-af8b-43e9-83e6-0a53fafd0806.jpg)

I still think this is Dalamud problem rather than Echoglossian's, though. Dalamud has problem with Korean fonts. I've tried posting about this in their Discord a couple times but no luck.

![2](https://user-images.githubusercontent.com/56755347/163798611-a9fe1b76-1208-43db-bb62-f0d38ff41139.png)

(Same happens with AXIS fonts)

For extra context, FFXIV doesn't have Korean fonts and will display all Korean in "=", same thing in Dalamud too. Korean players have been using a mod to display Korean characters ingame(take a closer look at my chat log), but I do not exactly know about inner workings. Probably it replaces the font with the one from the Korean client.

**Comment by lokinmodar** [comment]
> Hi, I really appreciate the update today. Your plugin really helped playing 6.0 before it stopped working.
> 
> As far as I remember Korean displayed fine back then, but for some reason now it's missing Korean fonts now.
> 
> ![1](https://user-images.githubusercontent.com/56755347/163797817-81436828-af8b-43e9-83e6-0a53fafd0806.jpg)
> 
> I still think this is Dalamud problem rather than Echoglossian's, though. Dalamud has problem with Korean fonts. I've tried posting about this in their Discord a couple times but no luck.
> 
> ![2](https://user-images.githubusercontent.com/56755347/163798611-a9fe1b76-1208-43db-bb62-f0d38ff41139.png)
> 
> (Same happens with AXIS fonts)
> 
> For extra context, FFXIV doesn't have Korean fonts and will display all Korean in "=", same thing in Dalamud too. Korean players have been using a mod to display Korean characters ingame(take a closer look at my chat log), but I do not exactly know about inner workings. Probably it replaces the font with the one from the Korean client.

Hello! For my plugin it shouldn't be happening because it enforces NotoSans on its windows. I'll need to have a deeper look into this. 

Do you select Axis to be used in dalamud? Also, which mod your friends are using? I want to see if I can port their fonts to Eglo. 

Thx in advance!

**Comment by KihwaH** [comment]
> Hello! For my plugin it shouldn't be happening because it enforces NotoSans on its windows. I'll need to have a deeper look into this.
> 
> Do you select Axis to be used in dalamud? Also, which mod your friends are using? I want to see if I can port their fonts to Eglo.
> 
> Thx in advance!


Tested with both AXIS enabled and disabled on Dalamud. Both AXIS enabled and disabled affects the font of the translation box overlay, which might indicate font enforcement isn't working in my instance. I'll keep tinkering with the settings and see if anything changes.

Here's the mod:
https://cdn.discordapp.com/attachments/361913574848724992/408914452768096256/fk.7z

This file isn't being maintained, just shared among Korean FFXIV communities. Just simply dropping it into game folder makes it work. Also since this file is from 2017, it uses font before 4K update.

**Comment by lokinmodar** [comment]
> > Hello! For my plugin it shouldn't be happening because it enforces NotoSans on its windows. I'll need to have a deeper look into this.
> > Do you select Axis to be used in dalamud? Also, which mod your friends are using? I want to see if I can port their fonts to Eglo.
> > Thx in advance!
> 
> Tested with both AXIS enabled and disabled on Dalamud. Both AXIS enabled and disabled affects the font of the translation box overlay, which might indicate font enforcement isn't working in my instance. I'll keep tinkering with the settings and see if anything changes.
> 
> Here's the mod: https://cdn.discordapp.com/attachments/361913574848724992/408914452768096256/fk.7z
> 
> This file isn't being maintained, just shared among Korean FFXIV communities. Just simply dropping it into game folder makes it work. Also since this file is from 2017, it uses font before 4K update.

I've found out the error with help of a fellow plugin dev friend. I'll release a fix for it <3 

and thx for the font file. I'll look into it <3

**Comment by KihwaH** [comment]
> I've found out the error with help of a fellow plugin dev friend. I'll release a fix for it <3 
> 
> and thx for the font file. I'll look into it <3

Glad it helped!

**Comment by lokinmodar** [comment]
> > I've found out the error with help of a fellow plugin dev friend. I'll release a fix for it <3
> > and thx for the font file. I'll look into it <3
> 
> Glad it helped!

The update is waiting review and soon will be available when reloading the game through XL.

**Comment by KihwaH** [comment]
Hi, tested the new version. I can see Noto Sans is applied, but now I have this problem:

English:
![eng](https://user-images.githubusercontent.com/56755347/163939268-132b8e82-a4c4-4ebb-a50e-d74ec9e302b3.JPG)

Chinese Simplified:
![zh](https://user-images.githubusercontent.com/56755347/163939308-a971b17c-78a1-4b09-84b1-87e75000c013.JPG)

Korean:
![han](https://user-images.githubusercontent.com/56755347/163939355-51e24e34-7dea-4ed2-95d1-7c8665172891.JPG)

Nepali:
![nep](https://user-images.githubusercontent.com/56755347/163941492-6db88cf7-9be5-49ef-9d8b-a63f0a07cab8.JPG)

Is this problem in just my case, or just CJK being a pain to deal with?

Also by the way `...\AppData\Roaming\XIVLauncher\installedPlugins\Echoglossian\2.99.2204.920\Font` does not seem to contain CJK fonts if this can be the problem.

**Comment by lokinmodar** [comment]
> Hi, tested the new version. I can see Noto Sans is applied, but now I have this problem:
> 
> English: ![eng](https://user-images.githubusercontent.com/56755347/163939268-132b8e82-a4c4-4ebb-a50e-d74ec9e302b3.JPG)
> 
> Chinese Simplified: ![zh](https://user-images.githubusercontent.com/56755347/163939308-a971b17c-78a1-4b09-84b1-87e75000c013.JPG)
> 
> Korean: ![han](https://user-images.githubusercontent.com/56755347/163939355-51e24e34-7dea-4ed2-95d1-7c8665172891.JPG)
> 
> Nepali: ![nep](https://user-images.githubusercontent.com/56755347/163941492-6db88cf7-9be5-49ef-9d8b-a63f0a07cab8.JPG)
> 
> Is this problem in just my case, or just CJK being a pain to deal with?
> 
> Also by the way `...\AppData\Roaming\XIVLauncher\installedPlugins\Echoglossian\2.99.2204.920\Font` does not seem to contain CJK fonts if this can be the problem.

Hello! Can you please delete the file  `...\AppData\Roaming\XIVLauncher\pluginConfigs\Echoglossian.json` and relaunch the game to see if it will download these CJK fonts? For some reason it did not download the fonts for you in background

**Comment by KihwaH** [comment]
> Hello! Can you please delete the file `...\AppData\Roaming\XIVLauncher\pluginConfigs\Echoglossian.json` and relaunch the game to see if it will download these CJK fonts? For some reason it did not download the fonts for you in background

After deleting that file Dalamud just removed the whole folder and I had to install Echoglossian again. After that fonts were still not downloaded and same problem occured. So I just tried downloading CJK fonts from [Echoglossian](https://github.com/lokinmodar/Echoglossian)/Font/ and putting in there and...

![nice](https://user-images.githubusercontent.com/56755347/164039719-ba4cdc2e-2435-4545-ab2a-6cf2e8937710.JPG)

Fixed.

By the way, those font files are huge. I expect most of them are same characters or include practically unused characters. [Current Noto Sans KR file from Google](https://fonts.google.com/noto/specimen/Noto+Sans+KR) is 4.5 MB for Regular size.

**Comment by KihwaH** [comment]
Extra stuff I found (pardon if there are duplicates):

- Overlay font scale has negative values (when set to negative text gets just invisible)
![scale](https://user-images.githubusercontent.com/56755347/164046384-e3347d0e-e7d9-48db-bbf6-05f4f6732197.png)
 
- These system messages get translated even when `Translate in-game dialogues` is off (these follow the font scale of in-game dialogs so I assumed this way. Tested with all 3 translate options off, only `Activate game text realtime translation` on)
![jump](https://user-images.githubusercontent.com/56755347/164047096-6e154f55-cffd-4c34-aa22-172aad8d3b44.png)

**Comment by lokinmodar** [comment]
> Extra stuff I found (pardon if there are duplicates):
> 
> * Overlay font scale has negative values (when set to negative text gets just invisible)
>   ![scale](https://user-images.githubusercontent.com/56755347/164046384-e3347d0e-e7d9-48db-bbf6-05f4f6732197.png)
> * These system messages get translated even when `Translate in-game dialogues` is off (these follow the font scale of in-game dialogs so I assumed this way. Tested with all 3 translate options off, only `Activate game text realtime translation` on)
>   ![jump](https://user-images.githubusercontent.com/56755347/164047096-6e154f55-cffd-4c34-aa22-172aad8d3b44.png)

Nice findings. I'll have to comb those options so they do not overlap or override each other. About the download it is weird that even deleting the config and reloading the game you still did not receive them. Do you have the XL folder added as an exception to your antivirus/windows defender? Also, can youu check if there is an `echoglossian.db` file in the `pluginConfigs\Echoglossian` folder?

**Comment by lokinmodar** [comment]
> > Extra stuff I found (pardon if there are duplicates):
> > 
> > * Overlay font scale has negative values (when set to negative text gets just invisible)
> >   ![scale](https://user-images.githubusercontent.com/56755347/164046384-e3347d0e-e7d9-48db-bbf6-05f4f6732197.png)
> > * These system messages get translated even when `Translate in-game dialogues` is off (these follow the font scale of in-game dialogs so I assumed this way. Tested with all 3 translate options off, only `Activate game text realtime translation` on)
> >   ![jump](https://user-images.githubusercontent.com/56755347/164047096-6e154f55-cffd-4c34-aa22-172aad8d3b44.png)
> 
> Nice findings. I'll have to comb those options so they do not overlap or override each other. About the download it is weird that even deleting the config and reloading the game you still did not receive them. Do you have the XL folder added as an exception to your antivirus/windows defender? Also, can youu check if there is an `echoglossian.db` file in the `pluginConfigs\Echoglossian` folder?

The negative overlay font scale was a request of some players that wanted to set the overlay translation box to go away without disabling it (weird, i know)

**Comment by KihwaH** [comment]
> Do you have the XL folder added as an exception to your antivirus/windows defender? 

Oops! However Windows Defender hasn't been complaining about Dalamud at all so I wasn't thinking of that. I added it as an exception now.

I removed `...\AppData\Roaming\XIVLauncher\pluginConfigs\Echoglossian.json` once again, which uninstalled the plugin, installed again, no CJK. 27 Font files. I added 5 CJK fonts so 32 were there.

>  Also, can youu check if there is an `echoglossian.db` file in the `pluginConfigs\Echoglossian` folder?

There is, slight peek via VS Code shows it's full of original and translated dialogues.

>  The negative overlay font scale was a request of some players that wanted to set the overlay translation box to go away without disabling it (weird, i know)

Yeah, I think there will be better ways to implement that...

**Comment by KihwaH** [comment]
I feel that you were in a hurry writing codes for this, take some time for your breath.

**Comment by lokinmodar** [comment]
> I feel that you were in a hurry writing codes for this, take some time for your breath.

I certainly was. But the major rework i'm doing for the 3.0 version of the plugin will address many of the problems the 2.x version still has. 

About the fonts not being downloaded, i'll provide a new mirror for them in the future becaus i think this is due to GitHub limitations and quotas...

**Comment by KihwaH** [comment]
> About the fonts not being downloaded, i'll provide a new mirror for them in the future becaus i think this is due to GitHub limitations and quotas...

I haven't looked at your code yet, but may I suggest using reliable source like [Debian repo](https://salsa.debian.org/fonts-team/fonts-noto-cjk/-/blob/master/Sans/OTC/NotoSansCJK-Regular.ttc)? I don't know if TTC can be used in your plugin, but this one file contains all CJK region fonts including Mono and only 18MB in size.

**Comment by lokinmodar** [comment]
> > About the fonts not being downloaded, i'll provide a new mirror for them in the future becaus i think this is due to GitHub limitations and quotas...
> 
> I haven't looked at your code yet, but may I suggest using reliable source like [Debian repo](https://salsa.debian.org/fonts-team/fonts-noto-cjk/-/blob/master/Sans/OTC/NotoSansCJK-Regular.ttc)? I don't know if TTC can be used in your plugin, but this one file contains all CJK region fonts including Mono and only 18MB in size.

I'll look into it. ttc files are not supported by ImGui tho... I'll maybe need to extract the contents form them

**Comment by lokinmodar** [comment]
I'll close this for the moment. Dalamud in the main branch does not support other translations to the UI so well.
