### ISSUE TITLE
Not opening Configuration 

### ISSUE THREAD

**Issue by kaktuszka** [lokinmodar/Echoglossian#38]
installation echoglossian and C++ and nothing what am I supposed to do ?
![Screenshot 2022-04-18 153544](https://user-images.githubusercontent.com/103942695/163816032-d23c61ca-ff8f-480f-9a94-8f8cc687613f.png)

**Comment by lokinmodar** [comment]
Hello! Please try relaunching the game to see if it fixes <3

**Comment by kaktuszka** [comment]
okey this fix thank you <3 you god Lokinmodar
