### ISSUE TITLE
not translating battle dialogue box

### ISSUE THREAD

**Issue by dkdasher** [lokinmodar/Echoglossian#40]
The dialog boxes that appear at the top of the screen when you are in a duty and the subtitles of the area intro cutscenes are not being translated, I wanted to know if that's the case or am I skipping some setting.

PT-BR >>
As caixas de diálogo que aparece na parte de cima da tela quando você está em uma duty e as legendas das cutscenes de introdução de área não estão sendo traduzidos, eu queria saber se é assim mesmo ou eu que estou pulando alguma configuração. Desculpa se alguma coisa em inglês não estiver fazendo muito sentido.

**Comment by lokinmodar** [comment]
> The dialog boxes that appear at the top of the screen when you are in a duty and the subtitles of the area intro cutscenes are not being translated, I wanted to know if that's the case or am I skipping some setting.
> 
> PT-BR >> As caixas de diálogo que aparece na parte de cima da tela quando você está em uma duty e as legendas das cutscenes de introdução de área não estão sendo traduzidos, eu queria saber se é assim mesmo ou eu que estou pulando alguma configuração. Desculpa se alguma coisa em inglês não estiver fazendo muito sentido.


Sobre as caixas de texto em batalha (Battle talk): elas tiveram uma alteração geral dentro do jogo e não consigo ainda as capturar de forma confiável. Somente as que são fora de instances ou quests funcionam no momento.
Sobre as falas brancas em cutscenes: elas ainda não são traduzidas nessa versão. Só quando eu liberar a versão 3 do plugin que irei incluir isso de vez, junto com as caixas que mostram escolhas para o Hero of Light fazer.

**Comment by lokinmodar** [comment]
Ajustado na versão 3.7.x
