### ISSUE TITLE
Font issues for Patch 6.2

### ISSUE THREAD

**Issue by charlie754** [lokinmodar/Echoglossian#42]
![font](https://user-images.githubusercontent.com/110186184/187307754-9df7c69e-38a8-4576-be05-172148668f2e.png)

Plugin can't show unicode characters in translation correctly, like Japanese/Chinese/Korean after 6.2 patch, how to fix this?

**Comment by lokinmodar** [comment]
> ![font](https://user-images.githubusercontent.com/110186184/187307754-9df7c69e-38a8-4576-be05-172148668f2e.png)
> 
> Plugin can't show unicode characters in translation correctly, like Japanese/Chinese/Korean after 6.2 patch, how to fix this?

Hello. I'll take a look into It. In the mean time, could you test the actual translation to see If the chars are broken there too?

**Comment by charlie754** [comment]
English and other languages like Spanish are fine, just Asian language characters are broken. :(

**Comment by charlie754** [comment]
nice! can't wait to see the update, much appreciate!!!!
