### ISSUE TITLE
Problems with showing certain letters when traslating to Hungarian

### ISSUE THREAD

**Issue by naedrik** [lokinmodar/Echoglossian#44]
Hi,
I noticed a problem with certain regional utf-8 characters in the dialogues.
For exapmle: ű, ő is showing almost like a = sign and it makes it somewhat hard to read out the words.

![2022-11-07 19_00_24-FINAL FANTASY XIV](https://user-images.githubusercontent.com/34134844/200383151-c92ce293-6bd0-4b48-9383-1e41977d8139.png)

**Comment by lokinmodar** [comment]
Hello! Thank you for the report! I'll check into this. Is the problem happening only when replacing the text in the Native ui text box?

**Comment by naedrik** [comment]
Hi, no. I just checked, it's working there. I should've checked that.

**Comment by lokinmodar** [comment]
> Hi, no. I just checked, it's working there. I should've checked that.

thanks for the info. i'll probably have to add hungarian to the list of languages only supported by the translation overlay since the in-game native font does not have the proper glyphs (hence the = sign in their place)...

**Comment by misternose** [comment]
Hello, letters such as ğ, ü, ö, ş, ç are not displaying correctly in the Turkish language.

![tl](https://github.com/lokinmodar/Echoglossian/assets/11158772/717fe43b-64c0-409b-8515-355cf04da39f)

**Comment by lokinmodar** [comment]
In this case you will need to use a font mod since the native game font does not have all the glyphs necessary. You can ask about it in the Penumbra server https://discord.gg/kVva7DHV4r
