### ISSUE TITLE
Same issue we had before, Chinese texts are not showing properly

### ISSUE THREAD

**Issue by charlie754** [lokinmodar/Echoglossian#48]
This issue is happening after 6.3 patch

Chinese alphabet are shown as "??????"

![image](https://user-images.githubusercontent.com/110186184/213476750-a6ccf115-8d96-4f56-b6b9-3eaa4cffb154.png)

**Comment by lokinmodar** [comment]
can you check If the required fonts are in the plugin folder?

Em qui., 19 de jan. de 2023 às 12:04, charlie754 ***@***.***>
escreveu:

**Comment by charlie754** [comment]
I guess it should be "[NotoSansCJKtc-Regular.otf](https://github.com/lokinmodar/Echoglossian/blob/APIv8/Font/NotoSansCJKtc-Regular.otf)" or "[NotoSansCJKhk-Regular.otf](https://github.com/lokinmodar/Echoglossian/blob/APIv8/Font/NotoSansCJKhk-Regular.otf)"

**Comment by lokinmodar** [comment]
i'll check and push an update later!

Em qui., 19 de jan. de 2023 às 12:33, charlie754 ***@***.***>
escreveu:

**Comment by lokinmodar** [comment]
Which language you selected as translation target?

> I guess it should be "[NotoSansCJKtc-Regular.otf](https://github.com/lokinmodar/Echoglossian/blob/APIv8/Font/NotoSansCJKtc-Regular.otf)" or "[NotoSansCJKhk-Regular.otf](https://github.com/lokinmodar/Echoglossian/blob/APIv8/Font/NotoSansCJKhk-Regular.otf)"

**Comment by tcfshcrw** [comment]
> Which language you selected as translation target?
> 
> > I guess it should be "[NotoSansCJKtc-Regular.otf](https://github.com/lokinmodar/Echoglossian/blob/APIv8/Font/NotoSansCJKtc-Regular.otf)" or "[NotoSansCJKhk-Regular.otf](https://github.com/lokinmodar/Echoglossian/blob/APIv8/Font/NotoSansCJKhk-Regular.otf)"

I think it will be Hanyu chinese simplified or chinese traditional.
I have same problem.

**Comment by lokinmodar** [comment]
Ok, I will check.

Em dom., 22 de jan. de 2023 às 20:11, tcfshcrw ***@***.***>
escreveu:

**Comment by charlie754** [comment]
still waiting to be fixed, much appreciate ~~~

**Comment by lokinmodar** [comment]
> 

is this still happening for you?

**Comment by tcfshcrw** [comment]
yes, still happened in traditional chinese
![image](https://github.com/lokinmodar/Echoglossian/assets/48719709/1d71730e-b180-468e-90d5-3b38ce3b1f11)
but english was ok.
![image](https://github.com/lokinmodar/Echoglossian/assets/48719709/052e08dd-bcaa-443a-8289-d2aa73f2d44f)

**Comment by lokinmodar** [comment]
> yes, still happened in traditional chinese ![image](https://user-images.githubusercontent.com/48719709/241339471-1d71730e-b180-468e-90d5-3b38ce3b1f11.png) but english was ok. ![image](https://user-images.githubusercontent.com/48719709/241339532-052e08dd-bcaa-443a-8289-d2aa73f2d44f.png)

i submitted an update to fix this and provide new troubleshooting measures inside the plugin config window. I'd like your feedback after it gets available to you

> still waiting to be fixed, much appreciate ~~~

**Comment by tcfshcrw** [comment]
> > yes, still happened in traditional chinese ![image](https://user-images.githubusercontent.com/48719709/241339471-1d71730e-b180-468e-90d5-3b38ce3b1f11.png) but english was ok. ![image](https://user-images.githubusercontent.com/48719709/241339532-052e08dd-bcaa-443a-8289-d2aa73f2d44f.png)
> 
> i submitted an update to fix this and provide new troubleshooting measures inside the plugin config window. I'd like your feedback after it gets available to you
> 
> > still waiting to be fixed, much appreciate ~~~

![image](https://github.com/lokinmodar/Echoglossian/assets/48719709/fb2815bb-d636-4b4c-aa0b-2f1abdcdb500)
Hi it's works.
many thanks!

**Comment by mokeling** [comment]
![image](https://github.com/lokinmodar/Echoglossian/assets/56252068/80f18663-2a60-43c5-9ef1-5e160e652201)
Well, I am still experiencing this problem, is it because it is not fixed or because I am using the language patch?

**Comment by lokinmodar** [comment]
> ![image](https://user-images.githubusercontent.com/56252068/241777591-80f18663-2a60-43c5-9ef1-5e160e652201.png) Well, I am still experiencing this problem, is it because it is not fixed or because I am using the language patch?

did you use the red button in the new "Troubleshooting" tab in the plugin config window?

**Comment by mokeling** [comment]
![image](https://github.com/lokinmodar/Echoglossian/assets/56252068/3093ebd8-7bcd-4f7f-9a0d-7c530abe46ac)
![image](https://github.com/lokinmodar/Echoglossian/assets/56252068/655b5ae7-6303-4330-9a14-6e13150be8d5)
When I clicked the “re-download” button, all of my game text became English, but the translation still went wrong. It only works properly when I don't use the language patch, which is probably the problem. It's so sad ; ;

**Comment by tcfshcrw** [comment]
> ![image](https://user-images.githubusercontent.com/56252068/241966742-3093ebd8-7bcd-4f7f-9a0d-7c530abe46ac.png) ![image](https://user-images.githubusercontent.com/56252068/241968904-655b5ae7-6303-4330-9a14-6e13150be8d5.png) When I clicked the “re-download” button, all of my game text became English, but the translation still went wrong. It only works properly when I don't use the language patch, which is probably the problem. It's so sad ; ;

the chinese patch have lots of problem, you should remove it.

**Comment by mokeling** [comment]
> > ![image](https://user-images.githubusercontent.com/56252068/241966742-3093ebd8-7bcd-4f7f-9a0d-7c530abe46ac.png) ![image](https://user-images.githubusercontent.com/56252068/241968904-655b5ae7-6303-4330-9a14-6e13150be8d5.png)当我点击“重新下载”按钮时，我所有的游戏文本都变成了英文，但翻译仍然出错。它只有在不使用语言补丁时才正常工作，这可能是问题所在。太可悲了 ; ;
> 
> 中文补丁有很多问题，你应该删除它。

Yeah，I will，thanks

**Comment by lokinmodar** [comment]
> > > ![image](https://user-images.githubusercontent.com/56252068/241966742-3093ebd8-7bcd-4f7f-9a0d-7c530abe46ac.png) ![image](https://user-images.githubusercontent.com/56252068/241968904-655b5ae7-6303-4330-9a14-6e13150be8d5.png)当我点击“重新下载”按钮时，我所有的游戏文本都变成了英文，但翻译仍然出错。它只有在不使用语言补丁时才正常工作，这可能是问题所在。太可悲了 ; ;
> > 
> > 
> > 中文补丁有很多问题，你应该删除它。
> 
> Yeah，I will，thanks

Sorry to hear the Chinese patch breaks this but I can't help you with that. I suggest you choose what you are going to use (the plugin or the patch) until they fix the patch. I'll close this since the font problem is solved
