### ISSUE TITLE
ChatGPT

### ISSUE THREAD

**Issue by Gabriel-OLM** [lokinmodar/Echoglossian#49]
Olá, eu não sei como funciona a API do ChatGPT, mas não teria como utilizar ela para traduzir os textos do jogo?

**Comment by lokinmodar** [comment]
> Olá, eu não sei como funciona a API do ChatGPT, mas não teria como utilizar ela para traduzir os textos do jogo?

Sim. Estou implementando um meio de usar a ferramenta.

**Comment by onlineid** [comment]
sounds great. ChatGPT translation is much much better. Looking forward to it.

**Comment by lokinmodar** [comment]
Finally implemented in the current release!

> sounds great. ChatGPT translation is much much better. Looking forward to it.
