### ISSUE TITLE
About Battle translate text box

### ISSUE THREAD

**Issue by HelloLazyWorld** [lokinmodar/Echoglossian#50]
About translate box can't adjust anything in "Battle talk settings" except overlay font color
but this box can adjust position by "Talk settings" 
and have some translate problem

![image](https://user-images.githubusercontent.com/114070750/225404394-a491d4d5-4e1c-4557-9e80-820a25651dc9.png)

### and here try after arrived to Gold Saucer (translate text from gold saucer not boss dialog)
![image](https://user-images.githubusercontent.com/114070750/225407647-2253cd42-5317-46ac-b9e2-bb66fe2aa6dc.png)
![image](https://user-images.githubusercontent.com/114070750/225408681-1297f574-6e4e-4ca4-a9f5-6cfc241e2611.png)

### and try after restart game 
![image](https://user-images.githubusercontent.com/114070750/225409672-e24b032b-1efd-4056-88d6-7c9a2b2205dd.png)

**Comment by lokinmodar** [comment]
> About translate box can't adjust anything in "Battle talk settings" except overlay font color but this box can adjust position by "Talk settings" and have some translate problem
> 
> ![image](https://user-images.githubusercontent.com/114070750/225404394-a491d4d5-4e1c-4557-9e80-820a25651dc9.png)
> 
> ### and here try after arrived to Gold Saucer (translate text from gold saucer not boss dialog)
> ![image](https://user-images.githubusercontent.com/114070750/225407647-2253cd42-5317-46ac-b9e2-bb66fe2aa6dc.png) ![image](https://user-images.githubusercontent.com/114070750/225408681-1297f574-6e4e-4ca4-a9f5-6cfc241e2611.png)
> 
> ### and try after restart game
> ![image](https://user-images.githubusercontent.com/114070750/225409672-e24b032b-1efd-4056-88d6-7c9a2b2205dd.png)

Oh i'm working to fix this. it seems some game update broke the code i'm using after they put the character portraits. Thanks for the report!

**Comment by lokinmodar** [comment]
Should be fixed as of v3.7.x
