### ISSUE TITLE
Add a function to check for Cyrillic characters

### ISSUE THREAD

**Issue by FAR747** [lokinmodar/Echoglossian#56]
Due to the existence of an unofficial Russian translation of the game, please add a function to check the string for Cyrillic to avoid translating already translated strings. 

Regex: `[ЁёА-я]`

_You can just make a parameter in settings and a bool function, I can write the logic for checking it myself._

**Comment by lokinmodar** [comment]
this issue is related to this one: https://github.com/lokinmodar/Echoglossian/issues/71
