### ISSUE TITLE
Translate quests

### ISSUE THREAD

**Issue by samulopez** [lokinmodar/Echoglossian#57]
It would be good to translate the quest title, description and steps. I know some work was done and this request is part of the TODO list, but I couldn't find a place to discuss it. 

I want to help with this request, and with more stuff like adding other translation engines, but I prefer to start with the quests. 

Because this work is big, I think it would be good to split it into several PRs:
- Journal accept
- ScenarioTree
- TodoList
- Journal + JournalDetails

Thoughts?

**Comment by lokinmodar** [comment]
> It would be good to translate the quest title, description and steps. I know some work was done and this request is part of the TODO list, but I couldn't find a place to discuss it.
> 
> I want to help with this request, and with more stuff like adding other translation engines, but I prefer to start with the quests.
> 
> Because this work is big, I think it would be good to split it into several PRs:
> 
> * Journal accept
> * ScenarioTree
> * TodoList
> * Journal + JournalDetails
> 
> Thoughts?

hello, my friend! I think that this is a good idea too. I have a discord server where we can speak more. Please e-mail me in dsouzaesouza[at]gmail.com so i can invite you!

**Comment by samulopez** [comment]
Hi, I sent you an email with my discord user `masuelol`. 

I started with the code. I have the code ready for `Journal accept` and `ToDoList`.  I'm working on `JournalDetail` and trying to find a way to show the quest description with line breaks without doing complex operations.

**Comment by lokinmodar** [comment]
Hi! Sorry for the delayed response. I'll add you in discord so we can speak
more. In the meantime, are you considering in your code the Sqlite database
saving for those translations?

Em seg., 15 de abr. de 2024 às 12:33, samulopez ***@***.***>
escreveu:

**Comment by samulopez** [comment]
work started here: https://github.com/lokinmodar/Echoglossian/pull/58

TODO:
- Translate the quest summary and store it on the DB.

**Comment by samulopez** [comment]
done here https://github.com/lokinmodar/Echoglossian/pull/60
