### ISSUE TITLE
Overlay for cutscenes subtitles

### ISSUE THREAD

**Issue by necobrn** [lokinmodar/Echoglossian#63]
Just a small request for the future, in the latest update it seems that cutscene-specific subtitles are now being translated (it appears that the first line of dialog doesn't translate, but then after that, it seems to work, not a big deal but just pointing out), even though in the changelog just says that only quests and descriptions are now working. I don't know if it was the intent but I'm happy that it's now working! 

![image](https://github.com/lokinmodar/Echoglossian/assets/86063786/e8a63cf1-d869-4d4f-82ef-41f55866bdfb)

The thing is, it has that weird micro-stutter that happens if you translate directly on the original text box UI. I prefer to use the overlay translation for that reason (and for comparing with the original text too, sometimes the translation can be a little funky and helps to learn english). If possible, it could be interesting to have the overlay option to have in cutscenes too, for comparing the text and alleviate the micro-stutter until it doesn't have a fix.

E de qualquer forma, muito obrigado pelo seu plugin, eu já uso a um tempo e agora que estou terminando as expansões, anda ajudando muito tanto a mim quanto meus amigos que não sabem inglês.

**Comment by lokinmodar** [comment]
Sim. Minha ideia é adicionar a overlay como opção, até pra resolver o problema das línguas que não usam o alfabeto latino ou têm muitos caracteres especiais e o jogo não dá suporte

**Comment by caumonruclua215** [comment]
Hi, is there any way i can turn this feature off temporarily? It's become unreadable for mine language whenever cutscene playout, and it's still translate even i disable it. 
![image](https://github.com/lokinmodar/Echoglossian/assets/43584738/98b96284-4b78-4ced-8019-8dd6abee0469)

**Comment by lokinmodar** [comment]
A fix that t will allow disabling it for the cutscenes will be up soon

Em dom., 2 de jun. de 2024 às 03:32, caumonruclua215 <
***@***.***> escreveu:

**Comment by lokinmodar** [comment]
Fixed in v.3.8.x
