### ISSUE TITLE
Asian characters not displaying properly

### ISSUE THREAD

**Issue by yomingo** [lokinmodar/Echoglossian#64]
I use the XIVLauncher and recently updated Dalamud and I think this plugin was also updated and in the latest version the chinese characters stopped working properly. See attached image 
![Screenshot 2024-05-13 130650](https://github.com/lokinmodar/Echoglossian/assets/4305973/35d20ef8-9aef-4273-b1db-560760f4d5a6)

I reinstalled the plugin and it wasn't fixed. This should be the latest version FF14(2024.04.23), XIVLauncher, Dalamud and Echoglossian

**Comment by lokinmodar** [comment]
Hello! Did you try forcing the redownload of the plugin assets in the plugin config window?

If not, can you try this and inform me if it fixed the issue for you?

**Comment by yomingo** [comment]
ahh, I figured it out. The problem was because I upgraded windows from 10 -> 11, and it switched the default chinese language settings. After clicking through various language settings in windows 11, I found a compatibility checkbox to use the older version of microsoft pinyin which fixed this for me. Sorry for the confusion.
