### ISSUE TITLE
Update for new expansion

### ISSUE THREAD

**Issue by CastGryff** [lokinmodar/Echoglossian#75]
Hi, I love this is getting updated again recently! Thanks for working on it! Do you have an estimated timeline that I can install it from in Dalamud again? It currently still showing it's outdated.

**Comment by lokinmodar** [comment]
> Hi, I love this is getting updated again recently! Thanks for working on it! Do you have an estimated timeline that I can install it from in Dalamud again? It currently still showing it's outdated.

We are working hard to fix all the stuff that broke with this new update :)
