### ISSUE TITLE
Update status for Dawntrail 

### ISSUE THREAD

**Issue by lokinmodar** [lokinmodar/Echoglossian#77]
Hello guys!

We are working hard to fix the plugin for Downtrail and we will update this with new status as soon as possible. Once updated, the plugin will be available through the Dalamud Plugin Installer as always.

Please hang on with us!

Best wishes to you all!!

**Comment by Zhanyee** [comment]
Esperando ansiosamente pela atualização pra poder jogar a downtrail :D

**Comment by Kingudabat** [comment]
me funciono en la mañana y ahora sale no disponible :O, paso algo?

**Comment by lokinmodar** [comment]
> me funciono en la mañana y ahora sale no disponible :O, paso algo?

Sí. Lo bloqueamos para que hagamos unos ajustes de bugs criticos que no dejavan que los usuarios pudessen jugar el juego

**Comment by guisouzanl** [comment]
Alguma estimativa de quando vai estar disponível novamente?

**Comment by lokinmodar** [comment]
> Alguma estimativa de quando vai estar disponível novamente?

Provavelmente amanhã na parte da noite, entretanto estamos trabalhando pra que seja antes

**Comment by Kingudabat** [comment]
Oki gracias, a mi me funciono bien con una api de deepl. tuve un cuelgue con los diálogos en combate.  ignoro si los textos flotantes deberían funcionar ( me refiero a los textos blancos sin cuadro) que suelen aparecer al principio de los Jefes. pero eso no se traducía.  por lo demás un poco de stutering si se traducían las misiones. pero  0  lag en los diálogos de cuadro al menos. Demas decir que muchas gracias por el esfuerzo :D

**Comment by dev-raphaelbrandao** [comment]
alguma previsão ?  <3

**Comment by Yagasaki7K** [comment]
Tem alguma coisa que a comunidade pode ajudar para facilitar esse lançamento?

**Comment by lokinmodar** [comment]
Olá pessoal! Estou nos testes finais pra soltar uma versão nova ainda hoje. Peço um pouco mais de paciência ♥️

Hello guys! I'm in the final test phase before releasing a new version today. Please hang on a little bit more ♥️

**Comment by TomasFrancia** [comment]
I just logged in after years to say thank you for this, u just fixed the little stuttering when using ingame interface for traduction. Thank you a lot for your work, never left us please! Greetings from Argentina

**Comment by lokinmodar** [comment]
> I just logged in after years to say thank you for this, u just fixed the little stuttering when using ingame interface for traduction. Thank you a lot for your work, never left us please! Greetings from Argentina

Thx for the support! The stuttering is finally gone!

**Comment by franciscoglop** [comment]
Hi! After enable plugin again I started having crashes when translating, this was fixed and is a issue of my installation? or still working in a fix?

**Comment by lokinmodar** [comment]
> Hi! After enable plugin again I started having crashes when translating, this was fixed and is a issue of my installation? or still working in a fix?

i need more info on what kind of crashes you're having. Please join the Dalamud discord server and post the generated .tspack file here https://discord.com/channels/581875019861328007/1084906540592549958

**Comment by lokinmodar** [comment]
Should be at least partially working on DTr as of v3.7.x
