### ISSUE TITLE
Translation only shows up when you run the same dialogue again

### ISSUE THREAD

**Issue by TeTeNu** [lokinmodar/Echoglossian#83]
Hi,
First of all, thanks a lot for your amazing work. Thanks to you, I can fully enjoy the game's plot. Even though I know English, the dialogues are often demanding in terms of vocabulary. After today's update, pooling works, but unfortunately not immediately. The translation only shows up when I run the dialogue for the second time. And it seems to be remembered, i.e. when I leave the NPC and approach him again, I pose immediately. Nothing shows up when you first run the dialogue. Either in cutscenes or with NPCs. Thanks again.

**Comment by samulopez** [comment]
Thank you for the report. I found the bug and will fix it today.
