### ISSUE TITLE
Dialogos fora da caixa

### ISSUE THREAD

**Issue by dev-raphaelbrandao** [lokinmodar/Echoglossian#85]
Olá, primeiramente queria agradecer pelo seu emepnho neste plugin, é fantastico jogar o FF14 em PT-BR graças a seu trabalho. comecei a jogar e me deparei que por algumas vezes por causa do meu idioma PT/BR as falas ficam grandes de mais e não cabem dentro da caixa de texto e ficam pra fora, existe alguma possibilidade de aumentar a caixa de texto da tradução ou até colocar uma cor de fundo para as letras que ficam fora da caixa?

--------------------------------------------------------

Hello, firstly I wanted to thank you for your effort on this plugin, it's fantastic to play FF14 in PT-BR thanks to your work. I started playing and I realized that sometimes, because of my PT/BR language, the lines are too big and don't fit inside the text box and stick out, is there any possibility of enlarging the translation text box or even put a background color for the letters that are outside the box?

**Comment by lokinmodar** [comment]
Olá! Já temos esse problema no nosso radar. Acredito que o fix que já fizemos não foi o suficiente e precisamos ver alternativas. Tem como mandar uma foto ou print do diálogo para testarmos?

Hello! This issue is already on our radar. I believe the fix we implemented was not enough and we are checking alternatives. In the mean time, can you share an image or screenshot of an example so we can test?

**Comment by dev-raphaelbrandao** [comment]
Assim que eu estiver fazendo quests e aparecer novamente da forma q indiquei eu envio o print. Obrigado pela resposta

**Comment by dev-raphaelbrandao** [comment]
![Captura de tela 2024-07-11 151256](https://github.com/lokinmodar/Echoglossian/assets/170434440/7bcad54e-f3b2-4d57-b39f-bcea74bbb01a)
Conforme indicado e solicitado, segue o print da situação

**Comment by FoxmaidenJH** [comment]
> ![Captura de tela 2024-07-11 151256](https://private-user-images.githubusercontent.com/170434440/347852476-7bcad54e-f3b2-4d57-b39f-bcea74bbb01a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MTA5MDIsIm5iZiI6MTcyMDcxMDYwMiwicGF0aCI6Ii8xNzA0MzQ0NDAvMzQ3ODUyNDc2LTdiY2FkNTRlLWYzYjItNGQ1Ny1iMzlmLWJjZWE3NGJiYjAxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxNTEwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTU5ODUwMGQzNDlhZDM1OTU3ZmQ0MmNmMTI2YWFiMmVmYWNiYjBiNjc1OTYyOTk2Y2U5YmQ3ZDkyZGJhMjEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fG3_4sMxxpsKTZc0-RfA6INm0XdZgjYCjKrhkucSaRY) Conforme indicado e solicitado, segue o print da situação

Eu ja tive esses diálogos e todos foram bem certinhos!
Sabe informar qual a sua resolução e se voce usa alguma opção de UI dinâmica? Pode ser isso!

**Comment by dev-raphaelbrandao** [comment]
Não, eu uso tudo normalzinho sem addons, o unico q eu uso de plugins é este

**Comment by guisouzanl** [comment]
Aqui também nunca tive esse problema. Pode ser algo relacionado a resolução

**Comment by dev-raphaelbrandao** [comment]
![Captura de tela 2024-07-11 224847](https://github.com/user-attachments/assets/b9dab38c-b8b9-441a-b0ff-1b424785c3e5)
Não creio que possa ser minhas configurações...

**Comment by FoxmaidenJH** [comment]
A sua "UI size" ta em 80% isso muda basicamente tudo!

Eu tentaria duas coisas: Mudar para Full screen para ele ficar em Full HD mesmo e testar!

Depois, mudar para 100% e ver se melhora! Na minha UI mesmo, eu deixo tudo em 80%-60%, mas eu mudo cada configuração e não geral!

Edit: O pior que isso pode mudar as caixas de diálogo e com isso, causar esse problema.

**Comment by dev-raphaelbrandao** [comment]
entao ela estava em 100% e nao funcionou, mudei pra 80%(-zoom) pra ve se resolvia e nao resolveu
