### ISSUE TITLE
Not Working Translate in-game dialogues at first time

### ISSUE THREAD

**Issue by evandde** [lokinmodar/Echoglossian#86]
Summary:
When using the Translate in-game dialogues feature, the translated dialogue window does not appear for the first instance of new sentences. The translated result is only displayed when the same dialogue is encountered again. This issue occurs consistently with both quest dialogues and general NPC dialogues.

Details:

Feature Affected: Translate in-game dialogues
Current Behavior: The translated dialogue window fails to appear for new sentences upon first encounter. The translation is only shown when the same dialogue is revisited.
Consistent Across: Quest dialogues and general NPC dialogues
Language Module Used: Korean
Additional Info: The issue persists across different language modules, not just Korean.

**Comment by franciscoglop** [comment]
Hi!

Checking this fixed to me:
![imagen](https://github.com/lokinmodar/Echoglossian/assets/86245193/e49f9e96-80fa-4ec9-a0d6-035d2d4ff482)
(Sorry for being in spanish. /eglo and 5th tab, there is just a check button)

**Comment by lokinmodar** [comment]
We are working on the fixes for these issues right now. We will push a fix when the work is complete

**Comment by lokinmodar** [comment]
Should be fixed as of v3.7.x
