### ISSUE TITLE
All the letters appear to be ?.

### ISSUE THREAD

**Issue by graceright** [lokinmodar/Echoglossian#9]
![화면 캡처 2021-10-03 110334](https://user-images.githubusercontent.com/41146255/135736877-8246b209-4869-4038-bada-ccb0c2bae908.jpg)
It seems to be a language without built-in fonts. my setting was Korean. 
anyway thank you for the application I really hope to use it if font problem is solved. :)

**Comment by lokinmodar** [comment]
Yes. It is a known issue. It has to do with Glyph Ranges. I'm working to solve it in the coming days.
Please look forward to it!

**Comment by GameveD** [comment]
Waiting for this fix, since option Replacing Original Text is causing stutter for me every time it had to translate.

**Comment by lokinmodar** [comment]
Fixed in the current version. Please update through FFXIVQuickLauncher
