### ISSUE TITLE
Tradução dos textos brancos em cutscenes

### ISSUE THREAD

**Issue by DevNataneto** [lokinmodar/Echoglossian#90]
Salveee, primeiramente gostaria de parabenizar vocês pelo excelente trabalho no plugin. 
Vocês fizeram e fazem um diferencial gigantesco na experiência de jogar Final Fantasy 14 de muitos players!!

Bom, minha dúvida é somente uma: Existe alguma forma de traduzir aqueles textos que passam durante algumas cutscenes específicas, aqueles textos em branco, que não aparecem em caixa de diálogo(normalmente aparecem durante alguma cutscene de apresentação de cenário ou quando algum personagem está narrando).

EXEMPLO, RETIRADO DE UM VIDEO DO YOUTUBE:

![image](https://github.com/user-attachments/assets/870820f4-83bf-4dd3-8d03-e163a5838f59)

**Comment by lokinmodar** [comment]
Sim. Esses textos terão a tradução habilitada assim que eu corrigir uns bugs. Provavelmentee no próximo update

**Comment by dev-raphaelbrandao** [comment]
@lokinmodar  tens previsão de qnd vai ficar ok a correção dos bugs?
