### ISSUE TITLE
Tradução nas Boss Fight

### ISSUE THREAD

**Issue by dev-raphaelbrandao** [lokinmodar/Echoglossian#91]
Oi meu consagrado, novamente agradeço pelos seu emepenho no Echoglossian, ontem fazendo algumas trials notei que a tradução está ficando desta forma que o print mostra, outra coisa que notei, que algum das traduções de dialogos maiores por vezes ele se repete no proximo dialogo e não traduz o que era suposto, existe alguma configuração ou ajuste da minha parte q eu posso resolver isso?

![Captura de tela 2024-07-15 020942](https://github.com/user-attachments/assets/ba97c1c1-075e-43d3-8ada-7ba34eb50d3d)

**Comment by lokinmodar** [comment]
Isso eu preciso ajustar em código. Está no meu radar. Sobre a duplicação, também estamos checando. Não tive esse erro da duplicação do meu lado, mas já foi reportado

> Oi meu consagrado, novamente agradeço pelos seu emepenho no Echoglossian, ontem fazendo algumas trials notei que a tradução está ficando desta forma que o print mostra, outra coisa que notei, que algum das traduções de dialogos maiores por vezes ele se repete no proximo dialogo e não traduz o que era suposto, existe alguma configuração ou ajuste da minha parte q eu posso resolver isso?
> 
> ![Captura de tela 2024-07-15 020942](https://private-user-images.githubusercontent.com/170434440/348846598-ba97c1c1-075e-43d3-8ada-7ba34eb50d3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzY2NzQsIm5iZiI6MTcyMTA3NjM3NCwicGF0aCI6Ii8xNzA0MzQ0NDAvMzQ4ODQ2NTk4LWJhOTdjMWMxLTA3NWUtNDNkMy04YWRhLTdiYTM0ZWI1MGQzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQyMDQ2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTRhMTg1NTU5MjUxZjI3ZTk2M2RiNTI0NGI3ODczNmZlMmRjMTNmZDA1YWE1NDA3NTI3OTNlNGJiNTQ0YTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5LFsJyA8sMgtLFD5VOTgJEc_dJd4bFnyW4ahwMzv4m0)

**Comment by dev-raphaelbrandao** [comment]
Obrigado amigo e um excelente trabalho <3

**Comment by lokinmodar** [comment]
Pode checar se na versão 3.7.x isso está resolvido?
