### ISSUE TITLE
Crashes on Steamdeck

### ISSUE THREAD

**Issue by eretz-debug** [lokinmodar/Echoglossian#95]
First of all, I'm grateful to be able to play Endwalker well with this plugin on the Steamdeck.

But it doesn't works well in Dawntrail.
When talking to an NPC, the translated language comes up and crashes. I tried changing the language or translation engine, but it crashes the same.

**Comment by lokinmodar** [comment]
which target language are you using?

**Comment by eretz-debug** [comment]
Used Korean first, and tested Spanish, Portuguese.

**Comment by lokinmodar** [comment]
Investigating! Need friends woth steamdeck to test this!

**Comment by samulopez** [comment]
I will check this one. What translator are you using? DeepL or Google translator?

**Comment by samulopez** [comment]
I could replicate the problem on Steam deck if I enable the overlay. I advise disabling the overlay on Steam deck until the problem is fixed.
